name: fintech_mobile_task
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg_provider: ^1.0.7
  gap: ^3.0.1
  hooks_riverpod: ^2.4.10
  intl: ^0.18.0
  modal_bottom_sheet: ^3.0.0-pre
  page_transition: ^2.1.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: any


flutter_gen:
  output: lib/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    json: true

  assets:
    enabled: true
    outputs:
      class_name: FinTechMobileTaskAssets

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: Stolzl
      fonts:
        - asset: assets/fonts/stolzl/Stolzl-Regular.ttf
          # weight: 700
    - family: HelveticaNeueCyr
      fonts:
        - asset: assets/fonts/helveticaneuecyr/HelveticaNeueCyr-Roman.ttf
          # weight: 700


